apiVersion: v1
kind: Service
metadata:
  name: my-smart-rollout-active
spec:
  type: NodePort
  selector:
    app: my-smart-rollout
  ports:
    - nodePort: 31000
      protocol: TCP
      port: 8080
      name: active-port