apiVersion: v1
kind: Service
metadata:
  name: my-smart-rollout-preview
spec:
  type: NodePort
  selector:
    app: my-smart-rollout
  ports:
    - nodePort: 31001
      protocol: TCP
      port: 8080
      name: preview-port