apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  managedFields:
  name: vault-nodeport
  namespace: vault
spec:
  ports:
  - nodePort: 30200
    port: 8200
    protocol: TCP
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  type: NodePort
