apiVersion: v1
kind: Service
metadata:
  name: backend-preview
spec:
  type: NodePort
  selector:
    app: interest
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 32001