apiVersion: v1
kind: Service
metadata:
  name: configmaps-example-preview
spec:
  type: NodePort
  selector:
    app: configmaps-example
  ports:
    - nodePort: 31001
      protocol: TCP
      port: 8080
      name: preview-port