apiVersion: v1
kind: Service
metadata:
  name: configmaps-example-active
spec:
  type: NodePort
  selector:
    app: configmaps-example
  ports:
    - nodePort: 31000
      protocol: TCP
      port: 8080
      name: active-port

